LLM-Judged RAG Benchmarking
SAP-samples/btp-genai-starter-kit pull request #92
Opened 2024-09-24 15:37 UTC by sreanikdk

An example is being added to evaluate the response from a RAG application (created with RetrievalQA chain) using LLM-as-a-judge approach.

2024-09-25 12:58 UTC, EvgeniiSkrebtcov requested changes

2024-09-25 12:58 UTC, EvgeniiSkrebtcov commented on scripts/step03_explore_examples/02_advanced_rag/src/benchmark.py
> +    class Config:
poetry lock refers to Pydantic V2, where usage of Config is obsolete: 

name = "pydantic"
**version = "2.8.2"**

https://docs.pydantic.dev/2.2/migration/#changes-to-config

2024-09-25 12:58 UTC, EvgeniiSkrebtcov commented on scripts/step03_explore_examples/02_advanced_rag/src/ingest.py
> +def load_terraform_docs_from_github():
This Function repeats the functionality, please consider moving it to [Utils](https://github.com/SAP-samples/btp-genai-starter-kit/tree/main/scripts/step03_explore_examples/utils/utils): https://github.com/SAP-samples/btp-genai-starter-kit/blob/50e3d13e0a9e9bdf2a7eff4221149986a24cab25/scripts/step03_explore_examples/01_naive_rag/library/ingest.py#L19

2024-09-25 12:58 UTC, EvgeniiSkrebtcov commented on scripts/step03_explore_examples/02_advanced_rag/src/ingest.py
> +def ingest_terraform_docs():
This Function repeats the functionality, please consider moving it to [Utils](https://github.com/SAP-samples/btp-genai-starter-kit/tree/main/scripts/step03_explore_examples/utils/utils): https://github.com/SAP-samples/btp-genai-starter-kit/blob/50e3d13e0a9e9bdf2a7eff4221149986a24cab25/scripts/step03_explore_examples/01_naive_rag/library/ingest.py#L36

2024-09-25 12:58 UTC, EvgeniiSkrebtcov commented on scripts/step03_explore_examples/02_advanced_rag/src/benchmark.py
> +        rating_match = re.search(r"Total rating: (\d+(\.\d+)?)", validation_result.content)
There's no handling for cases where the regex doesn't find a match, which could lead to an AttributeError when rating_match.group(1) is accessed.

2024-09-26 12:23 UTC, sreanikdk commented
Will close this PR and create a new one(incorporating the review comments) with a dedicated set of examples for RAG Benchmarking.

2024-09-26 12:23 UTC, closed without merging